#!/usr/bin/env python3
import os, sys
status = None
path = sys.argv[1]
while True:
	if "//" in path: path = path.replace("//","/")
	elif len(path) > 0 and path[len(path)-1] == "/": path = path[:-1]
	else: break	
if not os.path.exists(path):
	status = "does-not-exist"
elif os.path.isdir(path):
	status = "directory"
else:
	status = "file"
print(status)