#!/usr/bin/env bash

# colors.
purple="\033[95m"
cyan="\033[96m"
orange='\033[33m'
blue="\033[94m"
green="\033[92m"
yellow="\033[93m"
grey="\033[90m"
red="\033[91m"
end="\033[0m"

#! /bin/sh
# Executes the original ssh command.
# usage: ../original_ssh_command.sh
if [ "${SSH_ORIGINAL_COMMAND:-}" = "internal-sftp" ] ; then # sftp request
	/usr/lib/openssh/sftp-server
elif [ "${SSH_ORIGINAL_COMMAND:-}" = "/usr/lib/openssh/sftp-server" ] ; then # sftp request
	/usr/lib/openssh/sftp-server
elif [ -n "${SSH_ORIGINAL_COMMAND:-}" ] ; then # a command specified
	bash -c "$SSH_ORIGINAL_COMMAND"
	#sh -c "$SSH_ORIGINAL_COMMAND"
elif [ "$SSH_ORIGINAL_COMMAND" = "" ] ; then # no command specified
    #sh -il # (without color)
    bash -il # (with color)
else # unrecognized error.
	echo "Error: unrecognized command (#786223)."
	echo "Closing connection."
	exit 1
fi  

