#!/usr/bin/env bash

# import dev0s library.
curl -s https://raw.githubusercontent.com/vandenberghinc/dev0s/master/dev0s/lib/bash/import | bash 
if [[ "$OSTYPE" == "darwin"* ]] ; then source /usr/local/lib/dev0s/lib/bash/import --silent ; else . /usr/local/lib/dev0s/lib/bash/import --silent ; fi

# the alias.
alias="ssht00ls"

# the source name.
source_name=$alias

# the pypi package name (may differ from alias).
pypi_name=$alias

# boolean indicating whether the package is an pypi package.
pypi_package="true"

# boolean indicating whether to create a syst3m alias.
create_alias="true"

# pip requirements file (subpath) (leave "none" to ignore).
pip_requirements="/requirements/requirements.pip"

# apt requirements file (subpath) (leave "none" to ignore).
apt_requirements="/requirements/requirements.apt"

# brew requirements file (subpath) (leave "none" to ignore).
brew_requirements="/requirements/requirements.brew"

# install the source code to a lib path (leave "none" to ignore).
lib="/usr/local/lib/$alias/" 

# create an database directory (leave "none" to ignore).
database="/etc/$alias/" 

# create an database directory (leave "none" to ignore).
venv="none" 

# the supported operating systems.
supported_os="linux,macos"

# defaults.
source=$(source-path $(requirements-path $0))

# execute packge installer.
install-package \
    --alias $alias \
    --source $source \
    --source-name $source_name \
    --pypi-name $pypi_name \
    --pypi-package $pypi_package \
    --create-alias $create_alias \
    --pip-requirements $pip_requirements \
    --apt-requirements $apt_requirements \
    --brew-requirements $brew_requirements \
    --lib $lib \
    --database $database \
    --venv $venv \
    --supported-os $supported_os
    $@ \

